name: Build Resume PDF

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Generate timestamp
        id: timestamp
        run: echo "ts=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Build PDF from HTML
        run: |
          wkhtmltopdf \
            --enable-local-file-access \
            index.html reed-m-mcfadden-resume.pdf

      - name: Upload timestamped PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-${{ steps.timestamp.outputs.ts }}
          path: Reed_McFadden_Resume.pdf

      - name: Commit latest reed-m-mcfadden-resume.pdf to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add reed-m-mcfadden-resume.pdf
          git commit -m "Update latest reed-m-mcfadden-resume.pdf" || echo "No changes to commit"
          git push

